let newTotals = {
    nbrActivities: 0,
    distanceTotal: 0,
    durationTotal: 0,
    swimNbrActivities: 0,
    swimDistanceTotal: 0,
    swimDurationTotal: 0,
    bikeNbrActivities: 0,
    bikeDistanceTotal: 0,
    bikeDurationTotal: 0,
    runNbrActivities: 0,
    runDistanceTotal: 0,
    runDurationTotal: 0,
    otherNbrActivities: 0,
    otherDistanceTotal: 0,
    otherDurationTotal: 0,
};

let newTeamTotals = {
    teamUid: teamUid,
    teamName: teamName,
    nbrActivities: 0,
    distanceTotal: 0,
    durationTotal: 0,
    swimNbrActivities: 0,
    swimDistanceTotal: 0,
    swimDurationTotal: 0,
    bikeNbrActivities: 0,
    bikeDistanceTotal: 0,
    bikeDurationTotal: 0,
    runNbrActivities: 0,
    runDistanceTotal: 0,
    runDurationTotal: 0,
    otherNbrActivities: 0,
    otherDistanceTotal: 0,
    otherDurationTotal: 0,
};
let newUserTotals = {
    uid: uid,
    displayName: displayName,
    nbrActivities: 0,
    distanceTotal: 0,
    durationTotal: 0,
    swimNbrActivities: 0,
    swimDistanceTotal: 0,
    swimDurationTotal: 0,
    bikeNbrActivities: 0,
    bikeDistanceTotal: 0,
    bikeDurationTotal: 0,
    runNbrActivities: 0,
    runDistanceTotal: 0,
    runDurationTotal: 0,
    otherNbrActivities: 0,
    otherDistanceTotal: 0,
    otherDurationTotal: 0,
};

let newUserOrTeamResult =
{
    allRecord: false,
    teamRecord: false,
    teamUid,
    teamName,
    userRecord: false,
    uid: null,
    displayName: "",
    isThisMine: false,
    distanceTotal: 0,
    pointsTotal: 0,
    durationTotal: 0,
    nbrActivities: 0,
    swimDistanceTotal: 0,
    swimPointsTotal: 0,
    swimNbrActivities: 0,
    swimDurationTotal: 0,
    bikeDistanceTotal: 0,
    bikePointsTotal: 0,
    bikeNbrActivities: 0,
    bikeDurationTotal: 0,
    runDistanceTotal: 0,
    runPointsTotal: 0,
    runNbrActivities: 0,
    runDurationTotal: 0,
    otherDistanceTotal: 0,
    otherPointsTotal: 0,
    otherNbrActivities: 0,
    otherDurationTotal: 0,
}